# Generated by Django 4.2.27 on 2026-01-31 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('Skis', 'Skis'), ('Snowboards', 'Snowboards'), ('Boots', 'Boots'), ('Bindings', 'Bindings'), ('Poles', 'Poles'), ('Helmets', 'Helmets'), ('Goggles', 'Goggles'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Other', 'Other')], max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent - Like New'), ('Good', 'Good - Minor Wear'), ('Fair', 'Fair - Some Wear'), ('Used', 'Used - Significant Wear')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('items', models.ManyToManyField(related_name='sales', to='skiboerse.item')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='skiboerse.seller'),
        ),
    ]
