# Generated by Django 4.2.27 on 2026-02-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_number',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
