# Generated by Django 4.2.27 on 2026-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0002_seller_seller_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='acceptance_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
