# Generated by Django 4.2.27 on 2026-02-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0003_seller_acceptance_fee_paid_seller_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verified_for_return',
            field=models.BooleanField(default=False),
        ),
    ]
