# Generated by Django 4.2.27 on 2026-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0004_item_verified_for_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='verified_for_return',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Ski', 'Ski'), ('Snowboard', 'Snowboard'), ('Skischuhe', 'Skischuhe'), ('Snowboardboots', 'Snowboardboots'), ('Skibindung', 'Skibindung'), ('Snowboardbindung', 'Snowboardbindung'), ('Skistoecke', 'Skistoecke'), ('Helm', 'Helm'), ('Skibrille', 'Skibrille'), ('Bekleidung', 'Bekleidung'), ('Zubehoer', 'Zubehoer'), ('Sonstiges', 'Sonstiges')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent - Like New'), ('Good', 'Good - Minor Wear'), ('Fair', 'Fair - Some Wear'), ('Used', 'Used - Significant Wear')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='street_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
