# Generated by Django 4.2.27 on 2026-02-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0005_remove_item_verified_for_return_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
