# Generated by Django 4.2.27 on 2026-02-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
