# Generated by Django 4.2.27 on 2026-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0008_item_picked_up_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Bar'), ('card', 'Karte')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='returned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
