# Generated by Django 4.2.27 on 2026-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0009_add_payment_method_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_stolen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
