# Generated by Django 4.2.27 on 2026-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0010_add_is_stolen_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_major_seller',
            field=models.BooleanField(default=False),
        ),
    ]
