# Generated by Django 4.2.27 on 2026-09-17 16:10

from django.db import migrations, models
from django.db.models import F


def accept_existing_items(apps, schema_editor):
    """Treat everything that already exists as accepted.

    Items predate the acceptance flag, so leaving them NULL would mark the
    whole existing stock as not yet handed in and block it at the register.
    """
    Item = apps.get_model('skiboerse', 'Item')
    Item.objects.filter(accepted_at__isnull=True).update(accepted_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('skiboerse', '0011_seller_is_major_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(accept_existing_items, migrations.RunPython.noop),
    ]
